### ISSUE TITLE
Logout 

### ISSUE THREAD

**Issue by gaganpsinghkrishnais** [Dwarven/Twitter-OAuth#1]
HI thanks for the provided code. It works perfectly. As i am going to use the twitter login for the app. Is it possible to make user logout so that if he wants he can login with different twitter account.

Kingly provide the code if possible for the logout session destroy.

**Comment by Dwarven** [comment]
You can click the Logout button on the webview to logout the current account.
And then you can login with any twitter account.
<img width="578" alt="2016-04-08 9 56 41" src="https://cloud.githubusercontent.com/assets/5902224/14385831/f2461b2e-fdd4-11e5-8569-5f2a8b6ce2ae.png">
